#!/bin/bash

set -e

export PACKER_LOG=1
rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso ubuntu-trusty64.json
vagrant box remove vagrant_machine || true
vagrant box add vagrant_machine packer_virtualbox-iso_virtualbox.box
